tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#41A85F",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#a0afc5",
        "secondary-container": "#81b9ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#344355",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#004880",
        "outline": "#867366",
        "on-secondary": "#ffffff",
        "tertiary": "#516073",
        "surface-container": "#edeeef",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
        "surface-container-high": "#e7e8e9",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#0d1d2d",
        "tertiary-fixed-dim": "#b8c8de",
        "secondary-fixed-dim": "#a1c9ff",
        "on-tertiary-fixed-variant": "#39485a",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdcc3",
        "surface": "#f8f9fa",
        "on-surface": "#191c1d",
        "on-surface-variant": "#544438",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb77d",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-container": "#004980",
        "on-primary-container": "#663500",
        "tertiary-fixed": "#d4e4fb",
        "inverse-primary": "#ffb77d",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#001c37",
        "secondary-fixed": "#d2e4ff",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#f2994a",
        "surface-container-lowest": "#ffffff",
        "primary": "#41A85F",
        "secondary": "#1961a1",
        "outline-variant": "#d9c2b3"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "xs": "8px",
        "md": "24px",
        "sm": "16px",
        "container-max": "1280px",
        "base": "4px",
        "lg": "48px",
        "xl": "80px"
      },
      "fontFamily": {
        "label-sm": ["Prompt"],
        "display-lg": ["Prompt"],
        "body-lg": ["Prompt"],
        "display-lg-mobile": ["Prompt"],
        "body-md": ["Prompt"],
        "headline-md": ["Prompt"]
      },
      "fontSize": {
        "label-sm": ["13px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      },
    },
  }
}